services:
    ###
    ## RPC Services
    ###
    remoker.rpc.room:
        class: RemokerBundle\Controller\RoomController
        tags:
            - { name: gos_web_socket.rpc }

    remoker.rpc.story:
        class: RemokerBundle\Controller\StoryController
        tags:
            - { name: gos_web_socket.rpc }

    remoker.rpc.estimation:
        class: RemokerBundle\Controller\EstimationController
        tags:
            - { name: gos_web_socket.rpc }

    remoker.rpc.user:
        class: RemokerBundle\Controller\UserController
        tags:
            - { name: gos_web_socket.rpc }

    ###
    ## Topic (PubSub) Services
    ###
    remoker.topic:
        class: RemokerBundle\Topic\RemokerTopic
        tags:
            - { name: gos_web_socket.topic }

